# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: 
  branches:
    include:
      - master
  paths:
    include:
      - StoreApp
      - azure-pipelines.yml 

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: dotnet sdk 5.x
  inputs:
    packageType: 'sdk'
    version: '5.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: dotnet build
  workingDirectory: StoreApp


- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    workingDirectory: 'StoreApp'
    

- script: dotnet publish --configuration $(buildConfiguration) --output publish
  displayName: dotnet publish
  workingDirectory: StoreApp

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deployment
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(dbd464b4-3e87-49cc-88d7-2e30fc66c400)'
    appType: 'webApp'
    WebAppName: 'alex-StoreApp'
    packageForLinux: 'StoreApp/publish'